### ISSUE TITLE
memory leaks on bedrock-query and/or bedrock-shutdown

### ISSUE THREAD

**Issue by carns** [mochi-hpc/mochi-bedrock#4]
I think I'm seeing memory leaks on both the client and server side when these utilities are used.

They are probably not very important, but they do prevent automated test cases that use bedrock (like in the mochi-quintain service) from passing cleanly with address sanitizers if these tools are used.

The report from address sanitizer is very long, but a lot of it seems like it might just be some parsed json that wasn't released, e.g.:

```
    #0 0x7efd5eda19a7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
    #1 0x7efd5e8c5203 in json_object_object_add_ex /tmp/carns/spack-stage/spack-stage-json-c-0.15-4i2cra2gmog2tf6qstkw35ox4jbqbtfy/spack-src/json_object.c:608
    #2 0x7efd5a958c0c  (<unknown module>)
    #3 0x7efd5a957274  (<unknown module>)
    #4 0x7efd5a96063d  (<unknown module>)
    #5 0x7efd5ebdb573 in bedrock::DynLibServiceFactory::registerProvider(bedrock::FactoryArgs const&) /tmp/carns/spack-stage/spack-stage-mochi-bedrock-main-fqlbjyevtzxobws7dci7wwpgojb4xtjj/spack-src/src/DynLibServiceFactory.hpp:78
```

Note that this particular example is a json-c function (not nlohmann), so it might be comping from a sub-component rather than bedrock itself.

**Comment by mdorier** [comment]
I just fixed a bunch of memory leaks. The main problem was a circular shared pointer dependency preventing the ProviderManager (the class that manages providers in Bedrock) from being destroyed. The function you mentioned is in json-c, which bedrock doesn't used. What I suspect happened is that the ProviderManager not getting destroyed meant your quitain provider was not getting finalized.

I also find a memory leak down the Jx9 library in the bedrock server, but that's not something I can fix. Bedrock does call the finalization functions for the Jx9 engine.

Regarding memory leaks in bedrock-shutdown and bedrock-query, I found that these programs were not releasing some memory addresses (actually they were not supposed to, until the latest release of SSG changed the semantic of `ssg_get_group_member_addr` and made it create a copy which the user has to destroy).

The only two leaks remaining with valgrind in the bedrock-shutdown program (and I suspect bedrock-query as well) are the following:

```
==3917== 8 bytes in 1 blocks are definitely lost in loss record 1 of 2
==3917==    at 0x4847C73: realloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3917==    by 0x485F4A1: ssg_group_id_deserialize (ssg.c:1901)
==3917==    by 0x485FD54: ssg_group_id_load (ssg.c:2033)
==3917==    by 0x114053: resolveSSGAddresses (bedrock-shutdown.cpp:94)
==3917==    by 0x114053: main (bedrock-shutdown.cpp:31)
==3917==
==3917== 24 bytes in 1 blocks are definitely lost in loss record 2 of 2
==3917==    at 0x4847A25: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==3917==    by 0x485A24E: ssg_group_descriptor_create (ssg.c:2974)
==3917==    by 0x485F4C3: ssg_group_id_deserialize (ssg.c:1906)
==3917==    by 0x485FD54: ssg_group_id_load (ssg.c:2033)
==3917==    by 0x114053: resolveSSGAddresses (bedrock-shutdown.cpp:94)
==3917==    by 0x114053: main (bedrock-shutdown.cpp:31)
```

They seem to be down in SSG. Bedrock correctly calls ssg_group_destroy so SSG must be forgetting to free a couple of things.

Could you retry your use-case and see how it changes the asan report?

**Comment by carns** [comment]
Sorry for the delay.  I just now built a new mochi-bedrock@main with address sanitizer and tried it.  I'm still seeing similar leaks reported by address sanitizer, though.  The attached tarball has the json I'm using and the address sanitizer output from starting the server, waiting a few seconds, and running bedrock-shutdown against it.
[bedrock-asan-example-2022-05-22.tar.gz](https://github.com/mochi-hpc/mochi-bedrock/files/8073140/bedrock-asan-example-2022-05-22.tar.gz)

**Comment by carns** [comment]
Oh that report is from the server side, just to clarify.

**Comment by carns** [comment]
Both the bedrock-query and bedrock-shutdown utilities are asan clean now.

**Comment by mdorier** [comment]
All the memory leaks come from inside quintain. More specifically json-c objects allocated by quintain. I see that quintain's finalization callback ([here](https://github.com/mochi-hpc/mochi-quintain/blob/main/src/quintain-server.c#L40) does not free its json config. Maybe it's done somewhere else, but if so, I can't find where.

**Comment by carns** [comment]
Oh!  Great, we can close this ticket then and I'll reopen it on the quintain repo.

I guess the `(<unknown module>)` portions of the stack trace are from dynamically loaded provider libraries (in this case, quintain)?  That's too bad that address sanitizer can't identify it.
